// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased text-white relative min-h-screen`}
//       >
//         {/* 🌹 Rose Twilight Background with Top Glow */}
//         <div
//           className="absolute inset-0 z-0"
//           style={{
//             background:
//               "radial-gradient(ellipse 80% 60% at 50% 0%, rgba(244, 114, 182, 0.25), transparent 70%), #000000",
//           }}
//         />

//         {/* 🔹 Page Content Above Background */}
//         <div className="relative z-10">{children}</div>
//       </body>
//     </html>
//   );
// }

import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/Component/Header";
import Footer from "@/Component/Footer";
import DynamicShaderBackground from "@/Component/DynamicShaderBackground";
import { Toaster } from "react-hot-toast";

const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "MZ KODERS - Tech & Digital Solutions",
  description: "Modern web development, app development, AI, and digital services.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={plusJakarta.variable}>
      <body className="font-sans antialiased text-white relative min-h-screen bg-black">
        <DynamicShaderBackground />
        <Toaster
          position="top-right"
          toastOptions={{
            duration: 5000,
            style: {
              background: "rgba(30, 58, 95, 0.95)",
              color: "#fff",
              border: "1px solid rgba(255,255,255,0.2)",
            },
          }}
        />
        <div className="relative z-10 flex min-h-screen flex-col">
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
