// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased text-white relative min-h-screen`}
//       >
//         {/* 🌹 Rose Twilight Background with Top Glow */}
//         <div
//           className="absolute inset-0 z-0"
//           style={{
//             background:
//               "radial-gradient(ellipse 80% 60% at 50% 0%, rgba(244, 114, 182, 0.25), transparent 70%), #000000",
//           }}
//         />

//         {/* 🔹 Page Content Above Background */}
//         <div className="relative z-10">{children}</div>
//       </body>
//     </html>
//   );
// }

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LiquidEther from "@/Component/LiquidEther";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-white relative min-h-screen`}
      >
        {/* 🌊 Liquid Ether Background (Global) */}
        <LiquidEther />

        {/* 🔹 Page Content Above Background */}
        <div className="relative z-10">{children}</div>
      </body>
    </html>
  );
}
