import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GodRays from "@/Component/GodRays";

// Load Google fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Page metadata (works only in Server Component)
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black relative`}>
        {/* GodRays background for all pages */}
        <GodRays />
        
        {/* Your page content */}
        {children}
      </body>
    </html>
  );
}